---
"base_path": "."
"base_url": "https://api.crowdin.com"  # optional (for Crowdin Enterprise only)
"preserve_hierarchy": true
"pull_request_title": "chore(l10n): update translations"
"pull_request_labels": [
  "crowdin",
  "l10n"
]

"files": [
  {
    "source": "/*.md",
    "dest": "/%original_path%/%original_file_name%",
    "translation": "/locale/%two_letters_code%/%original_path%/%original_file_name%",
    "excluded_target_languages": [
      "en"
    ],
    "languages_mapping": {
      "two_letters_code": {
        # map non-two letter codes here, left side is crowdin designation, right side is babel designation
        "en-GB": "en_GB",
        "en-US": "en_US"
      }
    },
    "update_option": "update_as_unapproved"
  }
]
